SELECT [Id]
      ,[Name]
      ,[Description]
      ,[CategoryId]
      ,[PurchaseDate]
      ,[CurrencyId]
      ,[PurchasePrice]
      ,[SellPrice]
      ,[ImagePath]
      ,[LengthUnitId]
      ,[Length]
      ,[Heigth]
      ,[Depth]
      ,[Diameter]
      ,[VolumeUnitId]
      ,[Volume]
      ,[TagId]
      ,[StateId]
      ,[CreatedDate]
      ,[UpdatedDate]
      ,[Quantity]
      ,[ParentId]
      ,[Mass]
      ,[MassUnitId]
  FROM [InventoryMinData].[dbo].[Item]